README.md
topics-and-advance-readings/README.md
topics-and-advance-readings/did-ux.md

Adding a topic paper for RWOT 8

Where's the UX topic paper

---

topics-and-advance-readings/psdad.md

This is longer than 1-2 pages, because it seemed important to both describe the problem and sketch the solution enough to show that it can be practically solved.  We've had 20 years of people assuming namespace URIs were the best we can do (with me in the middle of that since late 2000). There's a high bar to considering another approach, I know.
I'm open to suggestions on what to trim, but I would like get the early bird discount, so maybe we can trim after that's done.

position paper on psdad, data format with secure semantics

---

README.md
topics-and-advance-readings/README.md
topics-and-advance-readings/universal-id-framework.md

Hi. This pull request contains my short topic paper

Universal ID Framework, by Shigya Suzuki

---

README.md
topics-and-advance-readings/README.md
topics-and-advance-readings/bootstrap_web-of-trust_reliance-lifecycle.md

Adding contribution from Matt Stone and Dan Burnett.

Add How to bootsrap trust in VC

---

topics-and-advance-readings/identity-for-people-places.md

Designing Identity for People and Places upload. Thanks

Topic Paper File Upload

---

README.md

This is my attempt to organize the README.md and include more information about each paper.
A couple notes: 
1. I attempted to pull the main idea out of each paper, but I am fairly new to this literature so please don't be offended if I did not get the main point (especially on the more technical papers) or if my hashtags are not accurate/complete. Feel free to PR to improve the organization if my interpretation could be improved.
2. This is my first GitHub PR in a public repo so I appreciate any feedback.
Thanks!

Proposed reorg of README.md with categories, hashtags, and key quotes

---

README.md

Added a link to the welcome pack PDF.
There's a PR at weboftrustinfo/website that has to be merged before the welcome pack pdf becomes available here.

achughes-add-link-to-welcome-pdf

---

topics-and-advance-readings/README.md
topics-and-advance-readings/diverse-teams.md

Hey there again,
I added my contact to the paper and the line in the second README as required.
Best wishes,
Karolin

Add contact and line in README

---

README.md

Still needs a link to the file.

Added Financing a Self-sovereign Technology Stack to the Use Cases

---

topics-and-advance-readings/README.md

Included by external reference, since I hope to expand on it a bit in coming days - hope that's OK.  Thanks!

First-draft advance reading paper/blog by Bryan Ford

---

README.md

Added #interoperability
(sorry, I forgot to accept collaborator invitation.)

Adding hashtag for Universal ID Framework

---

README.md
topics-and-advance-readings/did-fee-market-using-micropayments.md

Yancy Ribbens topic paper submission for RWOT8

topic paper submission

---

README.md
topics-and-advance-readings/README.md
topics-and-advance-readings/bringing-dependencies-btcr-wallet-to-swift-ecosystem.md

Added topic paper "Bringing the Dependencies of a BTCR Wallet to the Swift Ecosystem" by Wolf McNally for Blockchain Commons.

Added topic paper

---

README.md
topics-and-advance-readings/Proof_of_Key_Ownership_with_OpenID_Connect_Self-Issued_Identities.md
topics-and-advance-readings/README.md

Submission by Michael B. Jones

Proof of Key Ownership with OpenID Connect Self-Issued Identities

---

topics-and-advance-readings/README.md
topics-and-advance-readings/notebook-workbench.md

Proposal for using Jupyter notebooks, popular in the data-science community, as a vehicle for promoting adoption, fostering interoperability, supporting UX development, and expanding of the library of documented use-cases.

there is no kool-aid on jupyter

---

README.md
topics-and-advance-readings/README.md
topics-and-advance-readings/handshake.md

A submission by Boyma Fahnbulleh.

all: submit handshake topic paper

---

README.md
topics-and-advance-readings/README.md
topics-and-advance-readings/credentials-and-correlation.md

A submission to Rebooting the Web of Trust #8

Credentials and Correlation

---

README.md
topics-and-advance-readings/libp2p_did_auth..md

Looking forward to this meeting. Best, jonny

added lib2p2 draft topic paper for jonnycrunch

---

README.md

This addition is done on behalf of Maciej Laskus (@macieklearns2code) who is busy at the moment.

Added new link to README.md

---

README.md
topics-and-advance-readings/Providing_Decentralized_Identity_to_the_most_vulnerable_populations.md

'Providing Decentralized Identity to the most vulnerable populations'

Add a new paper 

---

README.md

Higher-definition Digital Identity

Added Topic

---

draft-documents/README.md

Add OIDC paper title to draft readme

Add OIDC paper title to draft readme

---

draft-documents/README.md
draft-documents/establishing_the-identity_of_the_issuer_by_the_verifier_in_verifiable_credentials.md

Initial draft of Establishing the Identity of the Issuer by the Verifier in Verifiable Credentials

Add Establising the Identity of the Issuer Paper

---

draft-documents/Use Cases and Research Directions for self-sovereign publication and journalism.md

Add working draft of journalism paper to draft documents folder

---

draft-documents/naming-survey.md

This submission is a survey on the propriety of human-meaningful names for self-sovereign identity. A primer on the topic will follow.

Human-meaningful names for SSI.

---

draft-documents/understanding-dids-in-greater-depth.md

indicate images are in media directory and move all MD headers to add one # to differentiate between Title and other headers

Update links to images and header level

---

draft-documents/did-auth-oidc.md
draft-documents/did-auth-vc-exchange.md

(Somehow managed to not submit the actual papers during the previous PR. So here they are.)

Add DID Auth and VC Exchange draft papers

---

README.md
topics-and-advance-readings/did-fee-market-using-micropayments.md

This PR updates the terminology used in the original submission.

Yancy ribbens topic paper corrections

---

draft-documents/understanding-dids-in-greater-depth.md

Addresses https://github.com/WebOfTrustInfo/rwot8-barcelona/issues/160

Added ; !syntax("abnf") to Appendix A. Cleaned up some whitespace.

---

draft-documents/understanding-dids-in-greater-depth.md

Reverts WebOfTrustInfo/rwot8-barcelona#164

Revert "Reset the DID ABNF - removed "$" and "!""

---

draft-documents/how-ssi-will-survive-capitalism.md

Hey Shannon, PR for the final Version of the Paper.

How SSI Will Survive Capitalism - Final Version

---

draft-documents/did-auth-oidc.md

* Clarifies the Terminology section (removes undefined references to "SSI model")
* Other minor edits per @selfissued's request.
(Shannon - I'll make the edits in the laid-out version as well)

SIOP paper - minor edits.
